--- 
playstore: 
    script: "echo 'Deploying...'"
    stage: deploy
    tags: 
        -unity
stages: 
    -test
    -build
    -deploy
unit-test: 
    -script: "d/: D:/Program\" Files\"/Unity/Editor/Unity
        -batchmode \
        -projectPath "/D:/Github\testing" \
        -runTests \
        -logfile \
        -testResults ./unit-tests.xml"
    stage: test
    tags: 
        -unity
unity-build: 
    script: "echo 'Building...'"
    stage: build
    tags: 
        -unity