--- 
playstore: 
    script: "echo 'Deploying...'"
    stage: deploy
    tags: 
        - unity
stages: 
    - test
    - build
    - deploy
unit-test: 
    script:
        - 'd: cd "D:\Program Files\Unity Hub\Editor\2019.2.5f1\Editor\"' 
        - '-batchmode -projectPath D:\Gebruikers\Iris Oostra\Documenten\GitHub\testing -runTests -testPlatform editmode -logfile -testResults
        ./unit-tests.xml | Out-Default'
    stage: test
    tags: 
        - unity
unity-build: 
    script: "echo 'Building...'"
    stage: build
    tags: 
        - unity