--- 
playstore: 
  script: "echo 'Deploying...'"
  stage: deploy
  tags: 
    - unity
stages: 
  - test
  - build
  - deploy
unit-test: 
  script:
    -d: cd "C:\Program' Files\Unity\Editor\Unity" \
    -batchmode: \
    -projectPath: "D:\Github\testing\" \
    -runTests: \
    -testPlatform: editmode \
    -logfile: \
    -testResults: ./unit-tests.xml | Out-Default \
  stage: test
  tags: 
    - unity
unity-build: 
  script: "echo 'Building...'"
  stage: build
  tags: 
    - unity
